### ISSUE TITLE
John Moehrke comments

### ISSUE THREAD

**Issue by JohnMoehrke** [IHE/mCSD-Whitepaper#5]
in general include links to the profiles.ihe.net page, profiles.ihe.net/ITI, mCSD, and the HIE Whitepaper. Possibly point at the HIE-Whitepaper section on directories.

1.0
- don't bother introducing FHIR. Start with the problem you are writing about.
- the term "registry" needs to be introduced for the specific context you mean. There are many uses of the word registry that are well outside of mCSD scope
- isn't the term we use "directory"
- "This whitepaper will describe some common uses where mCSD can be used to discover organizational, services, and system details. The mCSD implementation guide can be used in various configurations, each suited for a different use-case. The variations will be discussed in the context of these common use-cases."
- WHAT does this mean? "support aggregate and patient-level indicator reporting"   At what level does mCSD do patient-level details? This really concerns me.

that is as far as I read so far...

**Comment by lukeaduncan** [comment]
I have updated the document based on these and the discussion during the face to face.
